const axios = require('axios');
require('dotenv').config();

// 🏆 THE SQUAD
const ASSETS = [
  { id: 'GC=F', name: 'Gold (XAU/USD)' },
  { id: 'EURUSD=X', name: 'EUR/USD' },
  { id: 'GBPUSD=X', name: 'GBP/USD' },
  { id: 'JPY=X', name: 'USD/JPY' },
  { id: 'AUDUSD=X', name: 'AUD/USD' },
  { id: 'CAD=X', name: 'USD/CAD' },
  { id: 'CHF=X', name: 'USD/CHF' },
  { id: 'NZDUSD=X', name: 'NZD/USD' }
];

// 🛑 ANTI-SPAM MEMORY: Prevent duplicate alerts for the same asset within 4 hours
const alertCooldowns = {};
const COOLDOWN_MS = 4 * 60 * 60 * 1000; 

const sendTelegramMessage = async (text) => {
    const token = process.env.TELEGRAM_BOT_TOKEN;
    const chatId = process.env.TELEGRAM_CHAT_ID;

    if (!token || !chatId) {
        console.log("⚠️ Telegram credentials missing in .env file. Alert skipped.");
        return;
    }

    try {
        await axios.post(`https://api.telegram.org/bot${token}/sendMessage`, {
            chat_id: chatId,
            text: text,
            parse_mode: 'HTML' // Allows bold text and formatting
        });
        console.log("📲 Telegram Alert Sent Successfully!");
    } catch (error) {
        console.error("❌ Telegram Delivery Failed:", error.message);
    }
};

const scanMarketsForAlerts = async () => {
    console.log("🕵️‍♂️ BACKGROUND SCANNER: Checking all 8 assets for High-Probability Setups...");
    
    // We hit our own internal Node.js API to trigger the Python analysis
    const PORT = process.env.PORT || 10000;
    const LOCAL_API = `http://127.0.0.1:${PORT}/api/analyze`;

    for (const asset of ASSETS) {
        try {
            // 1. Check if this asset is currently on cooldown
            if (alertCooldowns[asset.id] && (Date.now() - alertCooldowns[asset.id] < COOLDOWN_MS)) {
                continue; 
            }

            // 2. Ask the Brain for an analysis
            const res = await axios.post(LOCAL_API, {
                symbol: asset.id,
                timeframe: '1h'
            });

            const data = res.data;
            
            // 3. 🛑 THE TRIGGER: Confidence >= 70% and a valid BUY/SELL signal
            if (data && data.confidence >= 70 && (data.signal === 'BUY' || data.signal === 'SELL') && data.tradeSetup) {
                const setup = data.tradeSetup;
                const signalIcon = data.signal === 'BUY' ? '🟢 BUY' : '🔴 SELL';

                const message = `
🚨 <b>AuraTrade AI Setup</b> 🚨

<b>Asset:</b> ${asset.name}
<b>Signal:</b> ${signalIcon}
<b>Win Probability:</b> ${data.confidence}%
<b>Master Bias:</b> ${data.trend}

🎯 <b>Execution Parameters:</b>
• <b>Entry:</b> ${setup.entry}
• <b>Stop Loss:</b> ${setup.stop_loss}
• <b>Take Profit:</b> ${setup.take_profit}
• <b>R:R Ratio:</b> 1:${setup.risk_reward}

🤖 <i>Auto-generated by Aura Brain</i>`;

                // Fire the message!
                await sendTelegramMessage(message);
                
                // Put this asset on cooldown
                alertCooldowns[asset.id] = Date.now(); 
            }
        } catch (error) {
            // Silent catch to prevent one broken API call from crashing the scanner loop
        }
    }
};

const startTelegramBot = () => {
    // Run the scanner every 15 minutes (900,000 milliseconds)
    setInterval(scanMarketsForAlerts, 15 * 60 * 1000);
    
    // Also run it once immediately (10 seconds after the server boots up)
    setTimeout(scanMarketsForAlerts, 10000);
    
    console.log("🤖 Telegram Sniper Bot Activated.");
};

module.exports = { startTelegramBot };